# DATA SCHOOLS TIPS USING SCIKIT-LEARN

In [5]:
#Data schools using scikit-learn package

#df = pd.DataFrame({'Shape':['square','square','oval','circle',np.nan]})

In [6]:
import numpy as np
import pandas as pd

In [23]:
data = {'Sibsp':[1,1,0,1,0,0],
         'Fare':[7.2500,71.2855,7.9250,53.1000,8.0500,8.4583],
        'Age':[22.0,38.0,26.0,35.0,35,np.nan]
        }

In [28]:
data


{'Sibsp': [1, 1, 0, 1, 0, 0],
 'Fare': [7.25, 71.2855, 7.925, 53.1, 8.05, 8.4583],
 'Age': [22.0, 38.0, 26.0, 35.0, 35, nan]}

In [30]:
df=pd.DataFrame(data)
df


Sibsp     Fare   Age
0      1   7.2500  22.0
1      1  71.2855  38.0
2      0   7.9250  26.0
3      1  53.1000  35.0
4      0   8.0500  35.0
5      0   8.4583   NaN

In [8]:
#df1 = pd.DataFrame({'Shape':['square','square','oval','circle',np.nan]})

In [27]:
#df1

In [40]:
#avilable in 0.21v onwards.first enable itertive imputer afte call iterrative imputer.
from sklearn.experimental import enable_iterative_imputer


In [32]:
from sklearn.impute import IterativeImputer

In [33]:
imputer_itr=IterativeImputer()

In [34]:
imputer_itr.fit_transform(df)

array([[ 1.        ,  7.25      , 22.        ],
       [ 1.        , 71.2855    , 38.        ],
       [ 0.        ,  7.925     , 26.        ],
       [ 1.        , 53.1       , 35.        ],
       [ 0.        ,  8.05      , 35.        ],
       [ 0.        ,  8.4583    , 28.50640581]])

In [39]:
# new in 0.22
from sklearn.impute import KNNImputer

In [37]:
knn_imputer= KNNImputer(n_neighbors=2)

In [38]:
knn_imputer.fit_transform(df)

array([[ 1.    ,  7.25  , 22.    ],
       [ 1.    , 71.2855, 38.    ],
       [ 0.    ,  7.925 , 26.    ],
       [ 1.    , 53.1   , 35.    ],
       [ 0.    ,  8.05  , 35.    ],
       [ 0.    ,  8.4583, 30.5   ]])

In [41]:
import sklearn

In [42]:
print(sklearn.__version__)

0.22.2.post1


In [43]:
#Difference between pipeline and make_pipeline
#Ans:Pipeline requires naming of steps,make_pipeline not.

#Difference between Columntrasformer and make_column_transformer
#Ans:Columntrasformer requires naming of steps,make_column_transformer not.


In [47]:
dic1 = {'Sibsp': [1,1,0,1,0,0],
         'Fare': [7.2500,71.2855,7.9250,53.1000,8.0500,8.4583],
         'Age' : [22.0,38.0,26.0,35.0,35,np.nan],
         'Sex':['Male','Femal','Male','Male','Female','Male'],
         'Color':['Red','Green','Blue','Red','Blue','Blue']
        }

In [48]:
data_df = pd.DataFrame(dic1)

In [49]:
data_df

Sibsp     Fare   Age     Sex  Color
0      1   7.2500  22.0    Male    Red
1      1  71.2855  38.0   Femal  Green
2      0   7.9250  26.0    Male   Blue
3      1  53.1000  35.0    Male    Red
4      0   8.0500  35.0  Female   Blue
5      0   8.4583   NaN    Male   Blue

In [ ]:
#Difference between pipeline and make_pipeline
#Ans:Pipeline requires naming of steps,make_pipeline not.

#Difference between Columntrasformer and make_column_transformer
#Ans:Columntrasformer requires naming of steps,make_column_transformer not.

In [50]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression

In [61]:
#1.Using make_column_transformer and make_pipeline

In [62]:
ohe = OneHotEncoder()
simpl_imp = SimpleImputer()
model_clf = LinearRegression()

In [63]:
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [64]:
ct = make_column_transformer((ohe,['Sex','Color']),(simpl_imp,['Age']),remainder = 'passthrough')

In [60]:
pipe = make_pipeline(ct,model_clf)

In [65]:
#2. Using Pipeline and ColumnTransformer

In [16]:
#Conver catagorical data into numerical data using pd.get_dummies() on dataframe.
import pandas as pd
import numpy as np

In [11]:
dic2 = {'Sibsp': [1,1,0,1,0,0],
         'Fare': [7.2500,71.2855,7.9250,53.1000,8.0500,8.4583],
         'Age' : [22.0,38.0,26.0,35.0,35,np.nan],
         'Sex':['Male','Femal','Male','Male','Female','Male'],
         'Color':['Red','Green','Blue','Red','Blue','Blue']
        }

In [17]:
data_obj = pd.DataFrame(dic2)
type(data_obj)

pandas.core.frame.DataFrame

In [14]:
model_data= pd.get_dummies(data_obj)

In [15]:
model_data

Sibsp     Fare   Age  Sex_Femal  Sex_Female  Sex_Male  Color_Blue  \
0      1   7.2500  22.0          0           0         1           0   
1      1  71.2855  38.0          1           0         0           0   
2      0   7.9250  26.0          0           0         1           1   
3      1  53.1000  35.0          0           0         1           0   
4      0   8.0500  35.0          0           1         0           1   
5      0   8.4583   NaN          0           0         1           1   

   Color_Green  Color_Red  
0            0          1  
1            1          0  
2            0          0  
3            0          1  
4            0          0  
5            0          0

In [ ]:
#concat data


In [18]:
#Conver catagorical data into numerical data using onehotencoder on array.
from sklearn.preprocessing import OneHotEncoder


In [24]:
X_values = data_obj[['Sex','Color']].values
X_values

array([['Male', 'Red'],
       ['Femal', 'Green'],
       ['Male', 'Blue'],
       ['Male', 'Red'],
       ['Female', 'Blue'],
       ['Male', 'Blue']], dtype=object)

In [21]:
type(X_values)

numpy.ndarray

In [26]:
ohe = OneHotEncoder(handle_unknown='ignore')
ohe

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='ignore', sparse=True)

In [27]:
ohe.fit_transform(X_values).toarray()

array([[0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.]])