In [1]:
import numpy as np
import pandas as pd
import os
from sklearn.impute import SimpleImputer



C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
details={'student_Id':[1,2,3,4,5],
           'Marks_10':[45,np.nan,54,89,np.nan],
           'Marks_12':[np.nan,65.0,68.0,88.0,87.0],
        'Marks_Grade':[56.0,67.0,57.0,np.nan,84.0],
              'state':[1.0,1.0,0.0,np.nan,1.0],
             'salary':[10,12,14,18,21]}
df= pd.DataFrame(details)

In [4]:
df

student_Id  Marks_10  Marks_12  Marks_Grade  state  salary
0           1      45.0       NaN         56.0    1.0      10
1           2       NaN      65.0         67.0    1.0      12
2           3      54.0      68.0         57.0    0.0      14
3           4      89.0      88.0          NaN    NaN      18
4           5       NaN      87.0         84.0    1.0      21

In [ ]:
#1.Missing value treatment

In [6]:
x = df.iloc[:,0:6].values
x

array([[ 1., 45., nan, 56.,  1., 10.],
       [ 2., nan, 65., 67.,  1., 12.],
       [ 3., 54., 68., 57.,  0., 14.],
       [ 4., 89., 88., nan, nan, 18.],
       [ 5., nan, 87., 84.,  1., 21.]])

In [30]:
#using mean missing value treatment
imp =SimpleImputer(missing_values=np.nan,strategy='mean')

In [31]:
imputer = imp.fit(x[:,1:5])

In [32]:
x[:,1:5] = imputer.transform(x[:,1:5])
x

array([[ 1.        , 45.        , 77.        , 56.        ,  1.        ,
        10.        ],
       [ 2.        , 62.66666667, 65.        , 67.        ,  1.        ,
        12.        ],
       [ 3.        , 54.        , 68.        , 57.        ,  0.        ,
        14.        ],
       [ 4.        , 89.        , 88.        , 66.        ,  0.75      ,
        18.        ],
       [ 5.        , 62.66666667, 87.        , 84.        ,  1.        ,
        21.        ]])

In [33]:
pd.DataFrame(x)

0          1     2     3     4     5
0  1.0  45.000000  77.0  56.0  1.00  10.0
1  2.0  62.666667  65.0  67.0  1.00  12.0
2  3.0  54.000000  68.0  57.0  0.00  14.0
3  4.0  89.000000  88.0  66.0  0.75  18.0
4  5.0  62.666667  87.0  84.0  1.00  21.0

In [39]:
#Using median missing value treatment
imp1 = SimpleImputer(missing_values=np.nan,strategy='median')
imputer1 = imp1.fit(x[:,1:5])
x[:,1:5] = imputer1.transform(x[:,1:5])

In [40]:
x

array([[ 1.        , 45.        , 77.        , 56.        ,  1.        ,
        10.        ],
       [ 2.        , 62.66666667, 65.        , 67.        ,  1.        ,
        12.        ],
       [ 3.        , 54.        , 68.        , 57.        ,  0.        ,
        14.        ],
       [ 4.        , 89.        , 88.        , 66.        ,  0.75      ,
        18.        ],
       [ 5.        , 62.66666667, 87.        , 84.        ,  1.        ,
        21.        ]])

In [41]:
# State column is catagorical data 
# need to apply mode (most-frequent)

In [42]:
imp =SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imputer = imp.fit(x[:,4:5])
x[:,4:5] = imputer.transform(x[:,4:5])
x

array([[ 1.        , 45.        , 77.        , 56.        ,  1.        ,
        10.        ],
       [ 2.        , 62.66666667, 65.        , 67.        ,  1.        ,
        12.        ],
       [ 3.        , 54.        , 68.        , 57.        ,  0.        ,
        14.        ],
       [ 4.        , 89.        , 88.        , 66.        ,  0.75      ,
        18.        ],
       [ 5.        , 62.66666667, 87.        , 84.        ,  1.        ,
        21.        ]])

In [46]:
#2. Missing values treatment using K-Nearestneighbour

In [44]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=2)
df = imputer.fit_transform(df)

In [45]:
df

array([[ 1. , 45. , 66.5, 56. ,  1. , 10. ],
       [ 2. , 49.5, 65. , 67. ,  1. , 12. ],
       [ 3. , 54. , 68. , 57. ,  0. , 14. ],
       [ 4. , 89. , 88. , 75.5,  1. , 18. ],
       [ 5. , 71.5, 87. , 84. ,  1. , 21. ]])

In [47]:
#2.Outlier tratment

In [48]:
outlier={'Department':['HR','HR','IT','IT','HR','IT','Mrketing','HR','Marketing','IT'],
           'Age':[21,33,35,36,34,33,34,32,31,55],
           'Experience':[1,12,12,12,11,13,12,10,2,35]
        }
df= pd.DataFrame(outlier)

In [49]:
df

Department  Age  Experience
0         HR   21           1
1         HR   33          12
2         IT   35          12
3         IT   36          12
4         HR   34          11
5         IT   33          13
6   Mrketing   34          12
7         HR   32          10
8  Marketing   31           2
9         IT   55          35

In [54]:
q1 =df.quantile(.25)
q3 = df.quantile(.75)
IQR = q3-q1

In [55]:
q1

Age           32.25
Experience    10.25
Name: 0.25, dtype: float64

In [56]:
q3

Age           34.75
Experience    12.00
Name: 0.75, dtype: float64

In [57]:
IQR

Age           2.50
Experience    1.75
dtype: float64

In [59]:
#Removing outliers using below syntax
df[~((df<(q1-1.5*IQR))|(df>(q3+1.5*IQR))).any(axis=1)]

Department  Age  Experience
1         HR   33          12
2         IT   35          12
3         IT   36          12
4         HR   34          11
5         IT   33          13
6   Mrketing   34          12
7         HR   32          10

In [60]:
#3.Feature scaling

In [61]:
featurescaling={'State':['California','Texas','Arizone','Utah','California'],
           'Age':[21,25,23,33,45],
           'Salary':[21000,25000,25000,30000,35000],
            'Purchage':['No','No','Yes','Yes','Yes']    
        }
df= pd.DataFrame(featurescaling)

In [62]:
df

State  Age  Salary Purchage
0  California   21   21000       No
1       Texas   25   25000       No
2     Arizone   23   25000      Yes
3        Utah   33   30000      Yes
4  California   45   35000      Yes

In [63]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_std = df.iloc[:,1:3].values
x_std = sc_x.fit_transform(x_std)
x_std

array([[-0.95454545, -1.28278913],
       [-0.5       , -0.45518324],
       [-0.72727273, -0.45518324],
       [ 0.40909091,  0.57932412],
       [ 1.77272727,  1.61383148]])

In [65]:
from sklearn.preprocessing import MinMaxScaler
sc_x = MinMaxScaler()
x_std = df.iloc[:,1:3].values
x_std = sc_x.fit_transform(x_std)
x_std

array([[0.        , 0.        ],
       [0.16666667, 0.28571429],
       [0.08333333, 0.28571429],
       [0.5       , 0.64285714],
       [1.        , 1.        ]])

In [66]:
from sklearn.preprocessing import RobustScaler
sc_x = RobustScaler()
x_std = df.iloc[:,1:3].values
x_std = sc_x.fit_transform(x_std)
x_std

array([[-0.4, -0.8],
       [ 0. ,  0. ],
       [-0.2,  0. ],
       [ 0.8,  1. ],
       [ 2. ,  2. ]])

In [67]:
from sklearn.preprocessing import MaxAbsScaler
sc_x = MaxAbsScaler()
x_std = df.iloc[:,1:3].values
x_std = sc_x.fit_transform(x_std)
x_std

array([[0.46666667, 0.6       ],
       [0.55555556, 0.71428571],
       [0.51111111, 0.71428571],
       [0.73333333, 0.85714286],
       [1.        , 1.        ]])