In [3]:
#factorial implementation
import numpy as np

In [9]:
num = int(input('Enter number :'))
factorial =1
if num < 0:
    print('Number must be positive')
elif num == 0:
    print('Factorial number is 1')
else:
    for i in range(1,num+1):
        factorial = factorial* i
print('Given number factorial is ',factorial)       

Enter number :7
Given number factorial is  5040


In [10]:
arr = np.arange(10,100)

In [3]:
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [11]:
#list wrapping


In [12]:
list1 =np.array([1,2,3,4,5,6])
print(list1)

[1 2 3 4 5 6]


In [19]:
# creating 5x5 zero arrays
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
# Creating linearly spaced vector
vector= np.linspace(0, 20, 10)
print(vector)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


In [29]:
output1 = np.asarray(x)
print(output1)

[1 2 3 4]


In [30]:
output2 = np.ndarray(x)
print(x)

[1, 2, 3, 4]


In [37]:
#Converting linear array into 2x2x2 3D array
arr = np.zeros(12)
arr3d = arr.reshape(3,2,2)
print(arr3d)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [38]:
arr = np.zeros(8)
arr3d = arr.reshape(2,2,2)
arr = arr3d.ravel()
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [43]:
#array indexing
arr = np.arange(5,50)
print(arr)
element = arr[6]
print(element)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
11


In [46]:
#array step   slice(start,stop & step)
step =np.arange(20)
array_slice = slice(1,10,2)
element = arr[6]
print(arr[array_slice])

[ 6  8 10 12 14]


In [47]:
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [48]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [49]:
arr[2:6]

array([2, 3, 4, 5])

In [51]:
#index lesser than 15
arr[:15]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,0,1,3]])
print(arr[0:2,0:2])

[[1 2]
 [5 6]]


In [61]:
#Numpy array Attributes
arr = np.array([[1,2,3],[4,5,6],[6,7,8]])
print('array :',arr)
print('')
print('Shape :',arr.shape)
print('ndim :',arr.ndim)
print('itemsize:',arr.itemsize)

array : [[1 2 3]
 [4 5 6]
 [6 7 8]]

Shape : (3, 3)
ndim : 2
itemsize: 4


In [62]:
# Creation routine
x = np.empty([3,2],dtype=int)
print(x)

[[770081472       669]
 [        0         0]
 [        1   5046341]]


In [63]:
#Array creation routine
x= np.zeros(5)

In [64]:
print(x)

[0. 0. 0. 0. 0.]


In [65]:
#Reading and Writing files
import os


In [67]:
os.getcwd()

'C:\\Users\\subbu\\Downloads'

In [72]:
file = np.loadtxt('C:\\Users\\subbu\\Downloads\\uan.txt')
np.savetxt('C:\\Users\\subbu\\Downloads\\uan1.txt',file)

ValueError: Expected 1D or 2D array, got 0D array instead

In [73]:
#Pandas


In [74]:
#creating pands series

In [4]:
import pandas as pd
series = pd.Series()
print(series)

Series([], dtype: float64)


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  


In [76]:
arr = np.array([10,20,30,40,50,60,70])
series = pd.Series(arr)
print(series)

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int32


In [79]:
# Creating series from python dictonary
data = {'a':10,'b':20,'c':30}
series = pd.Series(data)
print(series)

a    10
b    20
c    30
dtype: int64


In [80]:
s = pd.Series([10,20,30,40,50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [81]:
print(s[1:4])

1    20
2    30
3    40
dtype: int64


In [82]:
listx = [10,20,30,40,50]
print(pd.DataFrame(listx))


    0
0  10
1  20
2  30
3  40
4  50


In [84]:
data = [{'a':10,'b':20},{'a':30,'b':40},{'a':50,'b':70}]
table = pd.DataFrame(data)
print(table)

    a   b
0  10  20
1  30  40
2  50  70


In [85]:
data= {'one':pd.Series([1,2,3,4],index = ['a','b','c','d']),
       'two':pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])}
table = pd.DataFrame(data)
print(table)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  NaN    5


In [87]:
#To add extra dataframe to existing dataframe.
data = {'one':pd.Series([1,2,3],index=['a','b','c']),
        'two':pd.Series([1,2,3,4],index = ['a','b','c','d'])}
table = pd.DataFrame(data)
table['three']=pd.Series([1,2,3,4,5] ,index=['a','b','c','d','e'])
print(table)

   one  two  three
a  1.0    1      1
b  2.0    2      2
c  3.0    3      3
d  NaN    4      4


In [88]:
table1 = table
print(table1)

   one  two  three
a  1.0    1      1
b  2.0    2      2
c  3.0    3      3
d  NaN    4      4


In [90]:
del table['one']
print(table)


   two  three
a    1      1
b    2      2
c    3      3
d    4      4


In [95]:
print(table.pop('two'))

a    1
b    2
c    3
d    4
Name: two, dtype: int64


In [96]:
#Dataframe Row selection

In [97]:
print(table1)

   three
a      1
b      2
c      3
d      4


In [98]:
print(table)

   three
a      1
b      2
c      3
d      4


In [99]:
#To add extra dataframe to existing dataframe.
data = {'one':pd.Series([1,2,3],index=['a','b','c']),
        'two':pd.Series([1,2,3,4],index = ['a','b','c','d'])}
table_one = pd.DataFrame(data)
table_one['three']=pd.Series([1,2,3,4,5] ,index=['a','b','c','d','e'])
print(table_one)

   one  two  three
a  1.0    1      1
b  2.0    2      2
c  3.0    3      3
d  NaN    4      4


In [101]:
table_one.iloc[1:0]

Empty DataFrame
Columns: [one, two, three]
Index: []

In [104]:
#Row label selection using loc function
print(table_one.loc['c'])

one      3.0
two      3.0
three    3.0
Name: c, dtype: float64


In [105]:
print(table_one.loc['b'])

one      2.0
two      2.0
three    2.0
Name: b, dtype: float64


In [106]:
#Row index selection using iloc 

In [107]:
print(table_one.iloc[2])

one      3.0
two      3.0
three    3.0
Name: c, dtype: float64


In [111]:
#To add extra row to existing dataframe.
data = {'one':pd.Series([1,2,3],index=['a','b','c']),
        'two':pd.Series([1,2,3,4],index = ['a','b','c','d'])}
table_one = pd.DataFrame(data)
table_one['three']=pd.Series([1,2,3,4,5] ,index=['a','b','c','d','e'])
print(table_one)
row = pd.DataFrame([[0,0],[11,13],[17,19]],columns = ['two','three'])
table_one = table_one.append(row)
print(table_one)

   one  two  three
a  1.0    1      1
b  2.0    2      2
c  3.0    3      3
d  NaN    4      4
   one  two  three
a  1.0    1      1
b  2.0    2      2
c  3.0    3      3
d  NaN    4      4
0  NaN    0      0
1  NaN   11     13
2  NaN   17     19


In [1]:
# Basic functionlity of dataframe

In [25]:
data = {'odd':np.arange(1,100,2),
        'even':np.arange(0,100,2)}
print('Odd numbers :',data['odd'])
print('Even Numbers :',data['even'])
df = pd.DataFrame(data)
print('Sum:',df.sum())

Odd numbers : [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
Even Numbers : [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
Sum: odd     2500
even    2450
dtype: int64


In [26]:
df1 = pd.DataFrame(np.random.rand(5,4),
                  columns =['column1','column2','column3','column4'])
for key ,value in df1.iteritems():
    print(key,value)


column1 0    0.445326
1    0.542606
2    0.968612
3    0.820049
4    0.840092
Name: column1, dtype: float64
column2 0    0.141849
1    0.327482
2    0.185807
3    0.471064
4    0.249987
Name: column2, dtype: float64
column3 0    0.670404
1    0.790062
2    0.457740
3    0.701972
4    0.982666
Name: column3, dtype: float64
column4 0    0.226297
1    0.825806
2    0.055525
3    0.275991
4    0.305251
Name: column4, dtype: float64


In [11]:
#Iterrow

In [12]:
for key , val in df1.iterrows():
    print(key,val)
    

0 column1    0.255575
column2    0.327516
column3    0.349177
column4    0.414610
Name: 0, dtype: float64
1 column1    0.637813
column2    0.043160
column3    0.600397
column4    0.197035
Name: 1, dtype: float64
2 column1    0.243940
column2    0.498057
column3    0.190947
column4    0.683954
Name: 2, dtype: float64
3 column1    0.305907
column2    0.538189
column3    0.594118
column4    0.501087
Name: 3, dtype: float64
4 column1    0.817176
column2    0.290002
column3    0.119360
column4    0.426930
Name: 4, dtype: float64


In [13]:
#itertuples

In [14]:
for row in df.itertuples():
    print(row)

Pandas(Index=0, odd=1, even=0)
Pandas(Index=1, odd=3, even=2)
Pandas(Index=2, odd=5, even=4)
Pandas(Index=3, odd=7, even=6)
Pandas(Index=4, odd=9, even=8)
Pandas(Index=5, odd=11, even=10)
Pandas(Index=6, odd=13, even=12)
Pandas(Index=7, odd=15, even=14)
Pandas(Index=8, odd=17, even=16)
Pandas(Index=9, odd=19, even=18)
Pandas(Index=10, odd=21, even=20)
Pandas(Index=11, odd=23, even=22)
Pandas(Index=12, odd=25, even=24)
Pandas(Index=13, odd=27, even=26)
Pandas(Index=14, odd=29, even=28)
Pandas(Index=15, odd=31, even=30)
Pandas(Index=16, odd=33, even=32)
Pandas(Index=17, odd=35, even=34)
Pandas(Index=18, odd=37, even=36)
Pandas(Index=19, odd=39, even=38)
Pandas(Index=20, odd=41, even=40)
Pandas(Index=21, odd=43, even=42)
Pandas(Index=22, odd=45, even=44)
Pandas(Index=23, odd=47, even=46)
Pandas(Index=24, odd=49, even=48)
Pandas(Index=25, odd=51, even=50)
Pandas(Index=26, odd=53, even=52)
Pandas(Index=27, odd=55, even=54)
Pandas(Index=28, odd=57, even=56)
Pandas(Index=29, odd=59, even=58)


In [15]:
#world cup 
world_cup ={'Team':['West indies','West indies','India','Australlia','Pakistan','Srilanka',
                    'Australlia','Australlia','Australlia','Insia','Australlia'],
            'Rank':[7,7,2,1,6,4,1,1,1,2,1],
            'Year':[1975,1979,1983,1987,1992,1996,1999,2003,2007,2011,2015]}
df = pd.DataFrame(world_cup)
print(df)

           Team  Rank  Year
0   West indies     7  1975
1   West indies     7  1979
2         India     2  1983
3    Australlia     1  1987
4      Pakistan     6  1992
5      Srilanka     4  1996
6    Australlia     1  1999
7    Australlia     1  2003
8    Australlia     1  2007
9         Insia     2  2011
10   Australlia     1  2015


In [16]:
#Dataframe is group according to Team
print(df.groupby('Team').groups)

{'Australlia': Int64Index([3, 6, 7, 8, 10], dtype='int64'), 'India': Int64Index([2], dtype='int64'), 'Insia': Int64Index([9], dtype='int64'), 'Pakistan': Int64Index([4], dtype='int64'), 'Srilanka': Int64Index([5], dtype='int64'), 'West indies': Int64Index([0, 1], dtype='int64')}


In [17]:
#Dataframe is group according to Team & Rank

In [18]:
print(df.groupby(['Team','Rank']).groups)

{('Australlia', 1): Int64Index([3, 6, 7, 8, 10], dtype='int64'), ('India', 2): Int64Index([2], dtype='int64'), ('Insia', 2): Int64Index([9], dtype='int64'), ('Pakistan', 6): Int64Index([4], dtype='int64'), ('Srilanka', 4): Int64Index([5], dtype='int64'), ('West indies', 7): Int64Index([0, 1], dtype='int64')}


In [19]:
#groups can be iterable

In [21]:
grouped = df.groupby('Team')
for name , group in grouped:
    print(name)

Australlia
India
Insia
Pakistan
Srilanka
West indies


In [22]:
#single group can be select

In [23]:
print(grouped.get_group('India'))

    Team  Rank  Year
2  India     2  1983


In [24]:
print(grouped.get_group('Australlia'))

          Team  Rank  Year
3   Australlia     1  1987
6   Australlia     1  1999
7   Australlia     1  2003
8   Australlia     1  2007
10  Australlia     1  2015
